/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileInfoComm: typeof import('./components/fileInfoComm.vue')['default']
    FileListComm: typeof import('./components/fileListComm.vue')['default']
    HeaderComm: typeof import('./components/headerComm.vue')['default']
    IconButtonComm: typeof import('./components/iconButtonComm.vue')['default']
    ImgInfoComm: typeof import('./components/imgInfoComm.vue')['default']
    OrtherFileComm: typeof import('./components/ortherFileComm.vue')['default']
    PathComm: typeof import('./components/pathComm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComm: typeof import('./components/searchComm.vue')['default']
    ToolBarComm: typeof import('./components/toolBarComm.vue')['default']
    VideoInfoComm: typeof import('./components/videoInfoComm.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
