/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    FileInfoComm: typeof import('./components/fileInfoComm.vue')['default']
    FileListComm: typeof import('./components/fileListComm.vue')['default']
    HeaderComm: typeof import('./components/headerComm.vue')['default']
    ImgInfoComm: typeof import('./components/imgInfoComm.vue')['default']
    PathComm: typeof import('./components/pathComm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
